using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using TMPro;

public class CurrencyManager : MonoBehaviour
{
    public static CurrencyManager Instance;

    [Header("Money")]
    public int dollars = 0;
    public int pendingDollars = 0;

    // =========================================================
    // SPIN MONEY TRACKING
    // =========================================================

    /*
     * Gross positive money generated by the current spin.
     *
     * This intentionally tracks gains rather than net dollar delta:
     * if a future effect spends money during the same spin, Lucky Shot
     * still rewards the money that was actually earned.
     */
    public int MoneyEarnedThisSpin
    {
        get;
        private set;
    } = 0;


    /*
     * Gross money removed by GAMEPLAY LOSS effects during the current spin.
     *
     * This is deliberately separate from Spend():
     * - Spend() = normal costs/payments such as debt, shops and authored
     *   special cases such as Limbo's post-money Collect.
     * - LoseDollars() = gameplay consequences that should affect the spin's
     *   final net-money summary, such as Ambulance while it is in the Album.
     */
    public int MoneyLostThisSpin
    {
        get;
        private set;
    } = 0;


    public bool SpinMoneyLossTrackingActive
    {
        get;
        private set;
    } = false;


    public bool SpinEarningsTrackingActive
    {
        get;
        private set;
    } = false;

    [Header("UI")]
    public TMP_Text dollarsText;   // Dinero real: $X
    public TMP_Text pendingText;   // Dinero de la tirada: +X

    // =========================================================
    // UNITY
    // =========================================================

    private void Awake()
    {
        if (Instance != null && Instance != this)
        {
            Destroy(gameObject);
            return;
        }

        Instance = this;
    }

    private void Start()
    {
        UpdateDollarsUI();
        UpdatePendingUI();

        SetPendingVisible(false);
    }

    // =========================================================
    // REAL MONEY
    // =========================================================

    /// <summary>
    /// Añade dinero directamente al total real del jugador.
    ///
    /// Utilizar para:
    /// - recompensas ya resueltas
    /// - stickers que otorguen dinero fuera de una tirada
    /// - debug
    ///
    /// El dinero generado DURANTE una tirada debería entrar
    /// primero mediante AddPending().
    /// </summary>
    public void AddDollar(int amount)
    {
        if (SpinEarningsTrackingActive &&
            amount > 0)
        {
            MoneyEarnedThisSpin +=
                amount;
        }

        dollars += amount;

        /*
         * Por seguridad no permitimos dinero negativo
         * mediante AddDollar.
         *
         * Para gastar dinero debe utilizarse Spend().
         */
        if (dollars < 0)
            dollars = 0;

        UpdateDollarsUI();
    }

    /// <summary>
    /// Devuelve true si el jugador tiene dinero suficiente.
    /// </summary>
    public bool CanAfford(int amount)
    {
        if (amount <= 0)
            return true;

        return dollars >= amount;
    }

    /// <summary>
    /// Intenta gastar una cantidad de dinero.
    ///
    /// Devuelve:
    /// true  -> se ha podido pagar
    /// false -> no había dinero suficiente
    ///
    /// Esto será lo que utilizará la deuda.
    /// </summary>
    public bool Spend(int amount)
    {
        if (amount <= 0)
            return true;

        if (!CanAfford(amount))
            return false;

        dollars -= amount;

        UpdateDollarsUI();

        return true;
    }


    /// <summary>
    /// Removes up to amount dollars as a GAMEPLAY LOSS and returns the amount
    /// actually removed.
    ///
    /// Unlike Spend(), this never fails because the player has less than the
    /// requested amount: asking to lose $5 while owning $3 loses the remaining
    /// $3 and returns 3.
    ///
    /// When a physical spin is being tracked, this amount contributes to the
    /// final net-money summary. Ordinary costs/payments must continue to use
    /// Spend() so they are not accidentally classified as spin losses.
    /// </summary>
    public int LoseDollars(int amount)
    {
        int requested =
            Mathf.Max(
                0,
                amount
            );


        if (requested <= 0 ||
            dollars <= 0)
        {
            return 0;
        }


        int actualLoss =
            Mathf.Min(
                requested,
                dollars
            );


        dollars -=
            actualLoss;


        if (SpinMoneyLossTrackingActive)
        {
            MoneyLostThisSpin +=
                actualLoss;
        }


        UpdateDollarsUI();


        return
            actualLoss;
    }

    // =========================================================
    // PENDING MONEY
    // =========================================================

    /// <summary>
    /// Debe llamarse cuando comienza una nueva tirada real.
    ///
    /// Elimina cualquier dinero pendiente residual
    /// y prepara la UI.
    /// </summary>
    public void BeginSpin()
    {
        pendingDollars = 0;

        MoneyEarnedThisSpin = 0;
        MoneyLostThisSpin = 0;

        SpinEarningsTrackingActive = true;
        SpinMoneyLossTrackingActive = true;

        UpdatePendingUI();
        SetPendingVisible(true);
    }

    /// <summary>
    /// Añade dinero pendiente generado durante la tirada.
    ///
    /// Todavía NO forma parte del dinero real del jugador.
    /// </summary>
    public void AddPending(int amount)
    {
        if (SpinEarningsTrackingActive &&
            amount > 0)
        {
            MoneyEarnedThisSpin +=
                amount;
        }

        pendingDollars += amount;

        /*
         * Permitimos cantidades negativas en pending porque
         * en el futuro puede haber stickers/enemigos que
         * modifiquen la recompensa de una tirada.
         *
         * Pero nunca dejamos el resultado por debajo de cero
         * de momento.
         */
        if (pendingDollars < 0)
            pendingDollars = 0;

        SetPendingVisible(true);
        UpdatePendingUI();
    }

    /// <summary>
    /// Confirma el dinero pendiente de una tirada válida.
    ///
    /// Después de esto:
    /// pending = 0
    /// dollars += pending anterior
    /// </summary>
    public int CommitPending()
    {
        int amountCommitted = pendingDollars;

        if (amountCommitted > 0)
            dollars += amountCommitted;

        pendingDollars = 0;

        UpdateDollarsUI();
        UpdatePendingUI();
        SetPendingVisible(false);

        return amountCommitted;
    }

    /// <summary>
    /// Descarta el dinero pendiente.
    ///
    /// Se utilizará cuando una tirada no sea válida.
    /// </summary>
    public void ClearPending()
    {
        pendingDollars = 0;

        /*
         * ClearPending is the invalid-spin path.
         * Invalid spins cannot leave earnings tracking active.
         */
        MoneyEarnedThisSpin = 0;
        MoneyLostThisSpin = 0;

        SpinEarningsTrackingActive = false;
        SpinMoneyLossTrackingActive = false;

        UpdatePendingUI();
        SetPendingVisible(false);
    }

    // =========================================================
    // SPIN MONEY TRACKING
    // =========================================================

    /// <summary>
    /// Stops spin-earnings tracking and returns the gross positive
    /// money generated by that completed valid spin.
    ///
    /// The value is not reset immediately so it remains inspectable
    /// for debug. The next BeginSpin() starts again from zero.
    /// </summary>
    public int EndSpinEarningsTracking()
    {
        int total =
            MoneyEarnedThisSpin;

        SpinEarningsTrackingActive =
            false;

        return total;
    }


    /// <summary>
    /// Stops gameplay-loss tracking and returns the gross dollars removed by
    /// LoseDollars() during the completed valid spin.
    ///
    /// This may end later than earnings tracking. GameLogManager closes this
    /// counter only when it writes the final spin summary, so late gameplay
    /// losses can still be included without RouletteController knowing about it.
    /// </summary>
    public int EndSpinMoneyLossTracking()
    {
        int total =
            MoneyLostThisSpin;

        SpinMoneyLossTrackingActive =
            false;

        return total;
    }

    // =========================================================
    // RESET
    // =========================================================

    /// <summary>
    /// Reset explícito de economía.
    ///
    /// Probablemente el Game Over recargará la escena,
    /// pero dejamos esta función disponible para debug
    /// y futuros resets parciales.
    /// </summary>
    public void ResetCurrency()
    {
        dollars = 0;
        pendingDollars = 0;

        MoneyEarnedThisSpin = 0;
        MoneyLostThisSpin = 0;

        SpinEarningsTrackingActive = false;
        SpinMoneyLossTrackingActive = false;

        UpdateDollarsUI();
        UpdatePendingUI();
        SetPendingVisible(false);
    }

    // =========================================================
    // UI
    // =========================================================

    private void UpdateDollarsUI()
    {
        if (dollarsText != null)
            dollarsText.text = "$" + dollars;
    }

    private void UpdatePendingUI()
    {
        if (pendingText != null)
            pendingText.text = "+" + pendingDollars;
    }

    private void SetPendingVisible(bool visible)
    {
        if (pendingText != null)
            pendingText.gameObject.SetActive(visible);
    }
}
