using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class FlagPin : BaseFlagPin
{
    [Header("Rewards")]
    public int moneyReward = 1;

    [Header("Round Logic")]
    public RoundManager roundManager;

    // Money actually generated by this Flag Pin during the current spin.
    // RouletteController resets it when a real spin begins and reads it
    // only after the spin has been confirmed as valid.
    public int MoneyEarnedThisSpin { get; private set; } = 0;

    // --------------------------------------------
    // NUEVO: guardar posición y rotación original
    // --------------------------------------------
    [HideInInspector] public Vector3 originalPosition;
    [HideInInspector] public Quaternion originalRotation;
    [HideInInspector] public Transform originalParent;

    protected override void Awake()
    {
        base.Awake();

        if (roundManager == null)
            roundManager = FindObjectOfType<RoundManager>();

        // Guardamos su posición real al empezar
        originalPosition = transform.position;
        originalRotation = transform.rotation;
        originalParent = transform.parent;
    }

    public void ResetSpinEarnings()
    {
        MoneyEarnedThisSpin = 0;
    }

    // Este método lo usará WheelGenerator al restaurarlo
    public void RestoreToOriginal()
    {
        transform.SetParent(originalParent, true);
        transform.position = originalPosition;
        transform.rotation = originalRotation;
    }

    public override void RegisterHit()
    {
        base.RegisterHit();

        if (controller == null || CurrencyManager.Instance == null)
            return;

        CurrencyManager.Instance.AddPending(moneyReward);

        MoneyEarnedThisSpin += moneyReward;

        Debug.Log($"💰 Pending +{moneyReward} (pending total: {CurrencyManager.Instance.pendingDollars})");
    }
}