using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class FlagPin : BaseFlagPin
{
    public enum PlacementMode
    {
        FreePlacement,
        FixedAuthoredPosition
    }


    public enum SpinInteractionMode
    {
        LockMovementDuringSpin,
        AllowMovementPinnedHitsOnly
    }


    [Header("Placement Mode")]

    [Tooltip(
        "Free Placement: keeps the current behaviour; the player places and " +
        "can move the Flag Pin according to Spin Interaction.\n\n" +
        "Fixed Authored Position: the Transform authored in the scene is used " +
        "as the permanent pinned position. The Flag Pin starts placed, is " +
        "parented to the wheel while preserving that Transform, and cannot " +
        "be dragged."
    )]
    public PlacementMode placementMode =
        PlacementMode.FreePlacement;


    [Header("Rewards")]
    public int moneyReward = 1;


    [Header("Spin Interaction")]

    [Tooltip(
        "Lock Movement During Spin: the Flag Pin cannot be picked up once " +
        "a real spin has started.\n\n" +
        "Allow Movement Pinned Hits Only: the Flag Pin can still be moved " +
        "during the spin, but flapper contacts only count while the Flag " +
        "Pin is actually pinned to the wheel."
    )]
    public SpinInteractionMode spinInteractionMode =
        SpinInteractionMode.AllowMovementPinnedHitsOnly;


    [Header("Round Logic")]
    public RoundManager roundManager;

    // Money actually generated by this Flag Pin during the current spin.
    // RouletteController resets it when a real spin begins and reads it
    // only after the spin has been confirmed as valid.
    public int MoneyEarnedThisSpin { get; private set; } = 0;

    // --------------------------------------------
    // NUEVO: guardar posición y rotación original
    // --------------------------------------------
    [HideInInspector] public Vector3 originalPosition;
    [HideInInspector] public Quaternion originalRotation;
    [HideInInspector] public Transform originalParent;

    protected override void Awake()
    {
        base.Awake();

        if (roundManager == null)
            roundManager = FindObjectOfType<RoundManager>();

        // Guardamos su Transform authored real al empezar.
        originalPosition = transform.position;
        originalRotation = transform.rotation;
        originalParent = transform.parent;

        ConfigureInitialPlacementMode();
    }


    // =========================================================
    // PLACEMENT MODE
    // =========================================================

    private void ConfigureInitialPlacementMode()
    {
        if (placementMode !=
            PlacementMode.FixedAuthoredPosition)
        {
            return;
        }


        /*
         * The scene-authored Transform is the source of truth.
         *
         * We preserve world position/rotation exactly, then attach the pin to
         * the wheel so it naturally follows wheel rotation without needing
         * any per-frame placement/orientation logic.
         */
        if (wheelCenter != null &&
            transform.parent != wheelCenter)
        {
            transform.SetParent(
                wheelCenter,
                true
            );
        }


        isPlaced =
            true;

        isDragging =
            false;
    }


    protected override void Update()
    {
        if (placementMode ==
            PlacementMode.FixedAuthoredPosition)
        {
            /*
             * Fixed mode deliberately skips BaseFlagPin.Update().
             *
             * BaseFlagPin.Update() contains both drag handling and automatic
             * radial orientation. Neither should modify an authored fixed
             * Transform. The pin still receives flapper hits normally.
             */
            return;
        }


        base.Update();
    }


    public void ResetSpinEarnings()
    {
        MoneyEarnedThisSpin = 0;
    }

    // Este método lo usará WheelGenerator al restaurarlo
    public void RestoreToOriginal()
    {
        transform.SetParent(originalParent, true);
        transform.position = originalPosition;
        transform.rotation = originalRotation;
    }

    // =========================================================
    // SPIN INTERACTION
    // =========================================================

    protected override bool CanBeginDrag()
    {
        if (placementMode ==
            PlacementMode.FixedAuthoredPosition)
        {
            return false;
        }


        if (controller != null &&
            controller.SpinInProgress &&
            spinInteractionMode ==
                SpinInteractionMode.LockMovementDuringSpin)
        {
            return false;
        }

        return base.CanBeginDrag();
    }


    // =========================================================
    // HIT
    // =========================================================

    public override void RegisterHit()
    {
        /*
         * During a real spin, a loose Flag Pin can never generate money
         * or validation hits. This is what makes the movable mode safe.
         *
         * The same safety check also applies in locked mode.
         */
        if (controller != null &&
            controller.SpinInProgress &&
            !isPlaced)
        {
            return;
        }


        /*
         * Only award money if the hit was genuinely accepted by the
         * Flag Pin's own cooldown / RoundManager hit path.
         */
        if (!TryRegisterHitInternal(this))
            return;


        if (CurrencyManager.Instance == null)
            return;


        CurrencyManager.Instance.AddPending(
            moneyReward
        );

        MoneyEarnedThisSpin +=
            moneyReward;


        Debug.Log(
            $"💰 Pending +{moneyReward} " +
            $"(pending total: " +
            $"{CurrencyManager.Instance.pendingDollars})"
        );
    }
}