using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class FlagPin : BaseFlagPin
{
    public enum SpinInteractionMode
    {
        LockMovementDuringSpin,
        AllowMovementPinnedHitsOnly
    }


    [Header("Rewards")]
    public int moneyReward = 1;


    [Header("Spin Interaction")]

    [Tooltip(
        "Lock Movement During Spin: the Flag Pin cannot be picked up once " +
        "a real spin has started.\n\n" +
        "Allow Movement Pinned Hits Only: the Flag Pin can still be moved " +
        "during the spin, but flapper contacts only count while the Flag " +
        "Pin is actually pinned to the wheel."
    )]
    public SpinInteractionMode spinInteractionMode =
        SpinInteractionMode.AllowMovementPinnedHitsOnly;


    [Header("Round Logic")]
    public RoundManager roundManager;

    // Money actually generated by this Flag Pin during the current spin.
    // RouletteController resets it when a real spin begins and reads it
    // only after the spin has been confirmed as valid.
    public int MoneyEarnedThisSpin { get; private set; } = 0;

    // --------------------------------------------
    // NUEVO: guardar posición y rotación original
    // --------------------------------------------
    [HideInInspector] public Vector3 originalPosition;
    [HideInInspector] public Quaternion originalRotation;
    [HideInInspector] public Transform originalParent;

    protected override void Awake()
    {
        base.Awake();

        if (roundManager == null)
            roundManager = FindObjectOfType<RoundManager>();

        // Guardamos su posición real al empezar
        originalPosition = transform.position;
        originalRotation = transform.rotation;
        originalParent = transform.parent;
    }

    public void ResetSpinEarnings()
    {
        MoneyEarnedThisSpin = 0;
    }

    // Este método lo usará WheelGenerator al restaurarlo
    public void RestoreToOriginal()
    {
        transform.SetParent(originalParent, true);
        transform.position = originalPosition;
        transform.rotation = originalRotation;
    }

    // =========================================================
    // SPIN INTERACTION
    // =========================================================

    protected override bool CanBeginDrag()
    {
        if (controller != null &&
            controller.SpinInProgress &&
            spinInteractionMode ==
                SpinInteractionMode.LockMovementDuringSpin)
        {
            return false;
        }

        return base.CanBeginDrag();
    }


    // =========================================================
    // HIT
    // =========================================================

    public override void RegisterHit()
    {
        /*
         * During a real spin, a loose Flag Pin can never generate money
         * or validation hits. This is what makes the movable mode safe.
         *
         * The same safety check also applies in locked mode.
         */
        if (controller != null &&
            controller.SpinInProgress &&
            !isPlaced)
        {
            return;
        }


        /*
         * Only award money if the hit was genuinely accepted by the
         * Flag Pin's own cooldown / RoundManager hit path.
         */
        if (!TryRegisterHitInternal(this))
            return;


        if (CurrencyManager.Instance == null)
            return;


        CurrencyManager.Instance.AddPending(
            moneyReward
        );

        MoneyEarnedThisSpin +=
            moneyReward;


        Debug.Log(
            $"💰 Pending +{moneyReward} " +
            $"(pending total: " +
            $"{CurrencyManager.Instance.pendingDollars})"
        );
    }
}