using UnityEngine;

[CreateAssetMenu(
    fileName = "StickerWorkerAnt",
    menuName = "Stickers/Sticker Worker Ant"
)]
public class StickerWorkerAnt : StickerEffect, IAntSticker
{
    // =========================================================
    // CONFIGURATION
    // =========================================================

    [Header("Worker Ant")]

    [Tooltip(
        "Guaranteed money gained by every Worker Ant that activates in a Losing segment."
    )]
    [Min(0)]
    public int baseMoney =
        1;


    [Tooltip(
        "How many Ant stickers on the roulette are required for each shared colony bonus step."
    )]
    [Min(1)]
    public int antsPerColonyBonus =
        3;


    [Tooltip(
        "Additional money generated by the Worker Ant colony for every complete group of Ants. " +
        "This colony bonus is paid only ONCE per spin, regardless of how many Worker Ants activate."
    )]
    [Min(0)]
    public int colonyBonusPerGroup =
        1;


    // =========================================================
    // SHARED PER-SPIN STATE
    // =========================================================

    /*
     * Shared by ALL physical Worker Ants.
     *
     * The first Worker Ant that resolves in Losing during a spin may collect
     * the colony bonus. Every later Worker Ant still earns its own baseMoney,
     * but cannot collect the colony bonus again.
     *
     * The flag resets automatically after the complete gameplay resolution.
     */
    private static bool colonyBonusClaimedThisSpin =
        false;


    private static RoundManager
        colonyBonusResetRoundManager =
            null;


    // =========================================================
    // RESOLUTION
    // =========================================================

    public override void ResolveSpinLocation(
        BaseSticker owner,
        StickerSpinLocation location)
    {
        if (RoundManager.Instance != null &&
            !RoundManager.Instance.WasLastSpinValid)
        {
            return;
        }


        if (owner == null ||
            location !=
                StickerSpinLocation.NonWinningSegment)
        {
            return;
        }


        ResolveLosing(
            owner
        );
    }


    private void ResolveLosing(
        BaseSticker owner)
    {
        int antCount =
            StickerAntUtility
                .CountAntsOnWheel();


        int basePayout =
            Mathf.Max(
                0,
                baseMoney
            );


        int colonyBonus =
            CalculateColonyBonus(
                antCount
            );


        bool grantsColonyBonus =
            !colonyBonusClaimedThisSpin;


        int actualColonyBonus =
            grantsColonyBonus
                ? colonyBonus
                : 0;


        int totalPayout =
            SafeAdd(
                basePayout,
                actualColonyBonus
            );


        /*
         * The "once per spin" right is consumed by the first Worker Ant that
         * actually reaches its Losing activation, even if the current colony
         * bonus happens to be $0.
         *
         * This keeps resolution deterministic: later Workers cannot suddenly
         * collect a bonus because an earlier effect changed the Ant count.
         */
        if (grantsColonyBonus)
        {
            colonyBonusClaimedThisSpin =
                true;

            EnsureColonyBonusReset();
        }


        string description =
            BuildLogDescription(
                antCount,
                basePayout,
                actualColonyBonus,
                grantsColonyBonus
            );


        RegisterActivation(
            owner,
            StickerSpinLocation.NonWinningSegment,
            description,
            totalPayout,
            null
        );


        if (CurrencyManager.Instance != null &&
            totalPayout > 0)
        {
            CurrencyManager.Instance
                .AddDollar(
                    totalPayout
                );
        }


        Debug.Log(
            $"[WORKER ANT] Earned ${totalPayout}. " +
            $"Base = ${basePayout}, " +
            $"Ants on wheel = {antCount}, " +
            $"shared colony bonus = ${actualColonyBonus}, " +
            $"colony bonus already claimed = {colonyBonusClaimedThisSpin}."
        );
    }


    // =========================================================
    // SHARED BONUS RESET
    // =========================================================

    private static void EnsureColonyBonusReset()
    {
        RoundManager roundManager =
            RoundManager.Instance;


        if (roundManager == null)
            return;


        if (colonyBonusResetRoundManager != null &&
            colonyBonusResetRoundManager != roundManager)
        {
            colonyBonusResetRoundManager
                .OnGameplaySpinResolutionCompleted -=
                ResetColonyBonusAfterSpin;
        }


        colonyBonusResetRoundManager =
            roundManager;


        /*
         * Remove first so this can never accumulate duplicate subscriptions.
         */
        roundManager
            .OnGameplaySpinResolutionCompleted -=
            ResetColonyBonusAfterSpin;

        roundManager
            .OnGameplaySpinResolutionCompleted +=
            ResetColonyBonusAfterSpin;
    }


    private static void ResetColonyBonusAfterSpin()
    {
        colonyBonusClaimedThisSpin =
            false;


        if (colonyBonusResetRoundManager != null)
        {
            colonyBonusResetRoundManager
                .OnGameplaySpinResolutionCompleted -=
                ResetColonyBonusAfterSpin;
        }


        colonyBonusResetRoundManager =
            null;
    }


    // =========================================================
    // PAYOUT
    // =========================================================

    private int CalculateColonyBonus(
        int antCount)
    {
        int safeAntCount =
            Mathf.Max(
                0,
                antCount
            );


        int safeGroupSize =
            Mathf.Max(
                1,
                antsPerColonyBonus
            );


        int safeBonusPerGroup =
            Mathf.Max(
                0,
                colonyBonusPerGroup
            );


        int completeGroups =
            safeAntCount /
            safeGroupSize;


        long calculatedBonus =
            (long)completeGroups *
            safeBonusPerGroup;


        return
            calculatedBonus > int.MaxValue
                ? int.MaxValue
                : (int)calculatedBonus;
    }


    private int SafeAdd(
        int a,
        int b)
    {
        long total =
            (long)Mathf.Max(0, a) +
            Mathf.Max(0, b);


        return
            total > int.MaxValue
                ? int.MaxValue
                : (int)total;
    }


    // =========================================================
    // GAME LOG
    // =========================================================

    private string BuildLogDescription(
        int antCount,
        int basePayout,
        int colonyBonus,
        bool wasColonyBonusCollector)
    {
        string antWord =
            antCount == 1
                ? "Ant"
                : "Ants";


        if (wasColonyBonusCollector &&
            colonyBonus > 0)
        {
            return
                $"{antCount} {antWord} on the wheel. " +
                $"Base ${basePayout} + colony bonus ${colonyBonus}";
        }


        if (wasColonyBonusCollector)
        {
            return
                $"{antCount} {antWord} on the wheel. " +
                $"Base ${basePayout}; no colony bonus";
        }


        return
            $"{antCount} {antWord} on the wheel. " +
            $"Base ${basePayout}; colony bonus already collected";
    }


    // =========================================================
    // TOOLTIP
    // =========================================================

    protected override bool SupportsTooltipLocation(
        StickerSpinLocation location)
    {
        return
            location ==
                StickerSpinLocation.NonWinningSegment;
    }


    /*
     * Suggested Losing tooltip:
     *
     * Gain ${baseMoney}. Once per spin, Worker Ants collectively gain
     * +${colonyBonusPerGroup} for every {antsPerColonyBonus} Ants on the wheel.
     * Current colony bonus: ${colonyBonus}.
     *
     * Custom tokens:
     * {baseMoney}
     * {colonyBonusPerGroup}
     * {antsPerColonyBonus}
     * {antCount}
     * {completeGroups}
     * {colonyBonus}
     * {potentialPayout}
     */
    protected override string ResolveTooltipTokens(
        BaseSticker owner,
        StickerSpinLocation location,
        string template)
    {
        string resolved =
            base.ResolveTooltipTokens(
                owner,
                location,
                template
            );


        int antCount =
            StickerAntUtility
                .CountAntsOnWheel();


        int groupSize =
            Mathf.Max(
                1,
                antsPerColonyBonus
            );


        int completeGroups =
            Mathf.Max(
                0,
                antCount
            ) /
            groupSize;


        int colonyBonus =
            CalculateColonyBonus(
                antCount
            );


        int potentialPayout =
            SafeAdd(
                Mathf.Max(
                    0,
                    baseMoney
                ),
                colonyBonus
            );


        return
            resolved
                .Replace(
                    "{baseMoney}",
                    Mathf.Max(
                        0,
                        baseMoney
                    ).ToString()
                )
                .Replace(
                    "{colonyBonusPerGroup}",
                    Mathf.Max(
                        0,
                        colonyBonusPerGroup
                    ).ToString()
                )
                .Replace(
                    "{antsPerColonyBonus}",
                    groupSize.ToString()
                )
                .Replace(
                    "{antCount}",
                    Mathf.Max(
                        0,
                        antCount
                    ).ToString()
                )
                .Replace(
                    "{completeGroups}",
                    completeGroups.ToString()
                )
                .Replace(
                    "{colonyBonus}",
                    colonyBonus.ToString()
                )
                .Replace(
                    "{potentialPayout}",
                    potentialPayout.ToString()
                );
    }
}


